server:
  port:  8900 #程序启动的端口
spring:
  application:
    name: consumer-order-ribbon
user:
    url: http://localhost:7900/user/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
  instance:
    prefer-ip-address: true
