server:
  port:  7900 #程序启动的端口
spring:
  application:
    name: provider-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
  instance:
    prefer-ip-address: true